
title: Geospace Data Assimilation Working Group (GeoDAWG)

collections: [sections]
email: iaga.geodawg@gmail.com
baseurl: geodawg

sidebar:
  nav:sidebar-nav
  
sidebar-nav:
  - title: "About us"
  url: /
  - title: "Seminar Series"
  url: /

#theme: jekyll-theme-cayman
remote_theme: chrisbobbe/jekyll-theme-prologue
