
title: Geospace Data Assimilation Working Group (GeoDAWG)

remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
email: iaga.geodawg@gmail.com
baseurl: geodawg/_sections/


#sidebar:
#  nav:sidebar-nav
  
#sidebar-nav:
#  - title: "About us"
#  url: /
#  - title: "Seminar Series"
#  url: /

#theme: jekyll-theme-cayman
