title: Geospace Data Assimilation Working Group (GeoDAWG)

email: iaga.geodawg@gmail.com
baseurl: "/geodawg"
url: ""

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
