#theme: jekyll-theme-cayman

title: Geospace Data Assimilation Working Group (GeoDAWG)

remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
email: iaga.geodawg@gmail.com
baseurl: geodawg

